name: windows_single_instance_example
description: Demonstrates how to use the windows_single_instance plugin.

publish_to: "none"

environment:
  sdk: ">=2.16.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  libw_instance:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
