name: libw_instance
description: "Forces a single instance of your Windows app, bringing the existing window to the front when a new instance is opened"
version: "1.0.1"
homepage: "https://github.com/ng-huy/libw_instance"

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  win32: ">=2.5.0 <6.0.0"
  ffi: ">=1.0.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: WindowsSingleInstancePlugin
